name: Build and Push

on:
  push:
    tags:
      - 'v*.*.*'   # Only run when pushing version tags like v1.0.0

env:
  IMAGE_NAME: ryannguyen2708/flask-app

job:
  Build-Push:
    runs-on: ubuntu-latest

  steps:
  - name: Checkout source
    uses: actions/checkout@v4
    with:
          fetch-depth: 0  # so we can read tags

  - name: Extract version from tag
    run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV       

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3

  - name: Log in to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
  
  - name: Build and Push Docker image
    uses: docker/build-push-action@v6
    with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          ${{ env.IMAGE_NAME }}:latest